services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
      - .env:/var/www/html/.env

    environment:
      - DB_NAME=${DB_NAME?Database name is not set}
      - DB_USER=${DB_USER?User name is not set}
      - DB_PASS=${DB_PASS?Password is not set}
      - DB_HOST=${DB_HOST?Database host is not set}
      - DB_PORT=${DB_PORT?Database port is not set}

    ports:
      - "${BACKEND_PORT}:80"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "${FRONTEND_PORT}:80"

  db:
    image: mariadb:12.3

    environment:
      - MARIADB_DATABASE=${DB_NAME?Database name is not set}
      - MARIADB_USER=${DB_USER?User name is not set}
      - MARIADB_PASSWORD=${DB_PASS?Password is not set}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS?Root password is not set}
      
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
